config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  #root 'home#index'
  root 'friends#index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
    @current_user_friends = [];
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    if @friend.nil?
       respond_to do |format|
          format.html { redirect_to friends_url, notice: "Not Authorized To Edit This Friend" } 
          format.json { head :no_content }
       end  
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def about
    @name = "Kadir KALKAN"
    @mail = "kadirkalkanx@gmail.com"
    @url = "https://www.kadirkalkan.com"
    @github = "https://github.com/kadirkalkan"
    @source = "https://github.com/kadirkalkan/Rails_Project"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field form-group mb-2">
    <%= form.text_field :first_name, class: "form-control", placeholder: "First Name" %>
  </div>

  <div class = "field form-group mb-2">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>
  
  <div class = "field form-group mb-2">
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  
  <div class = "field form-group mb-2">
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>

  <div class = "field form-group mb-2">
    <%= form.text_field :twitter, class: "form-control", placeholder: "Twitter" %>
  </div>

  <div class = "field form-group mb-2">
    <%= form.number_field :user_id, id: :friend_user_id, 
    class: "form-control", 
      value: current_user.id, type: :hidden %>
  </div>

  <br>
  
  <div class = "actions">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class="card text-white bg-secondary mb-3">
  <div class="card-body">
     <p>
       <strong>First name:</strong>
       <%= friend.first_name %>
     </p>

     <p>
       <strong>Last name:</strong>
       <%= friend.last_name %>
     </p>

     <p>
       <strong>Email:</strong>
       <%= friend.email %>
     </p>

     <p>
       <strong>Phone:</strong>
       <%= friend.phone %>
     </p>

     <p>
       <strong>Twitter:</strong>
       <%= friend.twitter %>
     </p>
     <p>
       <strong>User Id:</strong>
       <%= friend.user_id %>
     </p>

     <br>

     <% if controller_name == "friends" && action_name == "index" %>
        <%= link_to "Show this friend", friend, class: "btn btn-dark", style: " width:100%" %>
     <% end %>
  </div>
</div>

app/views/friends/edit.html.erb
<div class="card">
  <div class="card-header">
    <h4>Editing friend</h4>
  </div>
  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>

<br>

<div>
  <% link_to "Show", @friend, class: "btn btn-secondary" %> 
  <%= link_to "Back", :back %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

<div class="card">
  <div class="card-header">
     <h4 style="display: inline-block;">Friends</h4>
     <%= link_to "New friend", new_friend_path, style:"float:right", class:"btn btn-success" %>
  </div>
  <div class="card-body">
     <div id="friends" class="row">
       <% @friends.each do |friend| %>
          <% if current_user == friend.user %>
            <% @current_user_friends.push(friend) %>
           <div class="col col-sm-3">
             <%= render friend %>
           </div>
         <% end %>
       <% end %>

         <% if @current_user_friends.count == 0 %>
          <h1>You have no friends :(</h1>
         <% end %>
     </div>
  </div>
</div>

<% else %>

<h1>Welcome To Friends App</h1>
<br>
<h5>If you want to have a friend list, You have to <b><%= link_to "Sign In!", new_user_session_path %></b></h5>

<% end %>

app/views/friends/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>New friend</h4>
  </div>
  <div class="card-body">
    <%= render "form", friend: @friend %>
  </div>
</div>

<br>

<div>
  <%= link_to "Back", friends_path %>
</div>

app/views/friends/show.html.erb
<div class="card">
  <div class="card-header">
    <h4>Show User</h4>
  </div>
  <div class="card-body" style="padding:1rem 2rem; ">
       <div class="row">
          <%= render @friend %>
       </div>
        <div class="row">
            <div class="col col-sm-3" style="padding:0px;">
              <%= link_to "Back", friends_path, class:"btn btn-primary" %>
            </div>
            <div class="col col-sm-9 d-flex justify-content-end" style="padding:0px;">
            
              <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-warning", style: 'margin-right:1%;' %>
              <%= button_to "Destroy", @friend,:onclick => "return confirm('Are you sure?')", form: {style: 'display:inline-block;'},  method: :delete, class:"btn btn-danger" %>
            </div>
        </div>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'Friend App', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'About Me', home_about_path, class: "nav-link" %>
        </li>
      </ul>
      <form class="d-flex">
       <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <% if user_signed_in? %>
             <li class="nav-item">
             <%= link_to 'Profile', edit_user_registration_path, class: "nav-link" %>
             </li>
             <li class="nav-item">
             <%= link_to 'Sign Out', destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "nav-link" %>
             </li>
           <% else %>
             <li class="nav-item">
             <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
             </li>
              <li class="nav-item">
             <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
             </li>
           <% end %>
       </ul>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 text-center">
  <h1 class="display-4"><b>About Me</b></h1>
  <p class="lead">My Name is Kadir KALKAN.
  	I'm a developer with over 3 years of experience. <br>I worked on different companies and took some serious roles on projects about optimization, stock analysis, E-Commerce etc.<br>
	I am currently teaching Full Stack Developer Course about .Net Technologies. <br>But mostly interested with Back End Development. </p>
</div>

<div class="container">
  <div class="row row-cols-2 text-center">
    <div class="col">
 	   <div class="card">
 	     <div class="card-header">
 	       <h4 class="my-0 font-weight-normal">Personal Information</h4>
 	     </div>
 	     <div class="card-body">
 	       <ul class="list-unstyled mt-3 mb-4">
 	         <li><b><i>If you want to learn more details about me</i></b></li>
 	         <li><br></li>
 	         <li>You can click the button below</li>
 	         <li>To reach my personal <b>Website</b></li>
 	       </ul>
 	       <a class="btn btn-lg btn-block btn-primary" target="blank" href=<%= @url %>>Go To Website</a>
 	     </div>
 	   </div>
    </div>
     <div class="col">
 	   <div class="card">
 	     <div class="card-header">
 	       <h4 class="my-0 font-weight-normal">Github</h4>
 	     </div>
 	     <div class="card-body">
 	       <ul class="list-unstyled mb-4">
 	         <li class="mb-2"><b><i>For more details about this project</i></b></li>
 	         <li><br></li>
 	         <li>You can check my <a class="btn btn-sm btn-outline-primary" target="blank" href=<%= @github %>><i class="fab fa-github"> <b>github</b></i></a> profile</li>
 	         <li class="mb-1" style="font-weight: 900; font-size: 25px;"><b><u>or</u></b></li>
 	         <li>Directly this website's <a class="btn btn-sm btn-outline-primary" target="blank" href=<%= @source %>><i class="fas fa-code"> source code</i></a></li>
 	       </ul>
 	     </div>
 	   </div>
    </div>
  </div>

</div>

app/views/layouts/_alerts.html.erb
<% if notice %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<p id="notice"><%= notice %></p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
        <br/>
        <%= render 'layouts/alerts' %>
        <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>